### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ds5678** [tkellogg/enyaml#3]
Can you please add a license file?

**Comment by tkellogg** [comment]
@ds5678 Yes, I absolutely can, but why? I hope you're not using `enyaml` for production purposes, it's very far from production-quality. Regardless, if you want a license, I can add one. Probably MIT.

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/issues/694

**Comment by tkellogg** [comment]
After consulting a few people, I've decided to clearly mark this repository as unmaintained and add a license to make it easier to fork & continue the work, if you desire. I'll likely archive this repo tomorrow.
